blank_issues_enabled: true
contact_links:
  - name: "ðŸ™‹ Ask a question"
    url: "https://github.com/PaulRBerg/prb-math/discussions/new/choose"
    about: "Ask questions and discuss with other community members"
